import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/section/Header";
import Footer from "@/components/section/footer";
import { Inter } from "next/font/google";
import StoreProvider from "@/providers/StoreProvider";
import AuthProvider from "@/providers/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MakoCinema",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth " data-scroll-behavior="smooth">
      <body className={`${inter.className} antialiased`}>
        <StoreProvider>
          <AuthProvider>
            <Header/>
              {children}
            <Footer/>
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
